tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "coreutils"
# brew "cscope"
brew "dive"
brew "docker-machine"
brew "exa"
brew "findutils"
# brew "gdbm"
# brew "gettext"
brew "git"
brew "groovy"
brew "homeshick"
brew "htop"
brew "istioctl"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "lazydocker"
brew "leiningen"
# brew "libyaml"
# brew "lua"
brew "macvim"
brew "micronaut"
# brew "mpdecimal"
brew "mtr"
# brew "ncurses"
# brew "oniguruma"
brew "openjdk"
# brew "openssl@1.1"
brew "packer"
# brew "pcre2"
brew "python@3.9"
# brew "readline"
# brew "ruby"
brew "shellcheck"
# brew "sqlite"
# brew "tcl-tk"
brew "terraform"
# brew "tree"
brew "vault"
# brew "xz"

cask "1password"
cask "docker"
cask "iterm2"
cask "kindle"
cask "microsoft-teams"
cask "network-radar"
cask "slack"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "virtualbox-extension-pack"
