#!/bin/bash -eu


export HOMESHICK_DIR="/usr/local"

if which brew >/dev/null 2>&1; then
  homeshick_sh="$(brew --prefix homeshick)/homeshick.sh"

  if [[ -f "${homeshick_sh}" ]]; then
    source "${homeshick_sh}"
  fi
fi
