#!/bin/bash -eu


# Configure Dock
# do we really want to kill-restart the Dock everytime we login?
# TBF, since these are persistent configs, we only really need to set them once.

defaults write com.apple.Dock orientation     -string left
defaults write com.apple.Dock autohide        -bool   true
defaults write com.apple.Dock autohide-delay  -float  2
defaults write com.apple.Dock magnification   -bool   false
defaults write com.apple.Dock largesize       -float  16
defaults write com.apple.Dock persistent-apps -array  "()"
defaults write com.apple.Dock show-recents    -bool   false

# Don't rearrange spaces
defaults write com.apple.Dock mru-spaces -bool false

# Allow quit Finder
defaults write com.apple.Finder "QuitMenuItem" -bool "true"

#kill "$(pgrep -f /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock)"


# Menubar

# Trackpad sensitivity (com.apple.AppleMultitouchTrackpad)

# Disable App quarantine popup
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Some folks are finding Big Sur's font smoothing too aggressive on external monitors.
# To disable it you can open a Terminal window and type:
defaults -currentHost write -g AppleFontSmoothing -int 0


# Keychain

# Keep aws-vault keychain open longer
security set-keychain-settings -t 900s aws-vault.keychain-db
